# Generated by Django 4.1.2 on 2022-12-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
